using UnityEngine;

using System;

static class ObstacleData
{
	public static String easyObstacles =
		@"<CHUNKS>

			<!-- Easiest Slalom -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-235</X_TWEAK>
					<TIMING>0.016</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-225</X_TWEAK>
					<TIMING>0.032</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-205</X_TWEAK>
					<TIMING>0.048</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-175</X_TWEAK>
					<TIMING>0.064</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-135</X_TWEAK>
					<TIMING>0.08</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-85</X_TWEAK>
					<TIMING>0.096</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-25</X_TWEAK>
					<TIMING>0.112</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-85</X_TWEAK>
					<TIMING>0.128</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-135</X_TWEAK>
					<TIMING>0.144</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-175</X_TWEAK>
					<TIMING>0.16</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-205</X_TWEAK>
					<TIMING>0.176</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-225</X_TWEAK>
					<TIMING>0.192</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-235</X_TWEAK>
					<TIMING>0.208</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.224</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<SIDE>left</SIDE>
					<TIMING>0.232</TIMING>
				</OBSTACLE>
			</CHUNK>

			<!-- Easier Slalom -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-235</X_TWEAK>
					<TIMING>0.016</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-225</X_TWEAK>
					<TIMING>0.032</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-205</X_TWEAK>
					<TIMING>0.048</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-175</X_TWEAK>
					<TIMING>0.064</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-135</X_TWEAK>
					<TIMING>0.08</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-85</X_TWEAK>
					<TIMING>0.096</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-25</X_TWEAK>
					<TIMING>0.112</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-25</X_TWEAK>
					<TIMING>0.128</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-30</X_TWEAK>
					<TIMING>0.144</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-40</X_TWEAK>
					<TIMING>0.16</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-60</X_TWEAK>
					<TIMING>0.176</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-90</X_TWEAK>
					<TIMING>0.192</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-130</X_TWEAK>
					<TIMING>0.208</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-180</X_TWEAK>
					<TIMING>0.224</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.24</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<SIDE>left</SIDE>
					<TIMING>0.248</TIMING>
				</OBSTACLE>
			</CHUNK>

			<!-- Easy Slalom -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-220</X_TWEAK>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-160</X_TWEAK>
					<TIMING>0.016</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-130</X_TWEAK>
					<TIMING>0.032</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-90</X_TWEAK>
					<TIMING>0.048</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-60</X_TWEAK>
					<TIMING>0.064</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-40</X_TWEAK>
					<TIMING>0.08</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-30</X_TWEAK>
					<TIMING>0.096</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-25</X_TWEAK>
					<TIMING>0.112</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-25</X_TWEAK>
					<TIMING>0.128</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-85</X_TWEAK>
					<TIMING>0.144</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-135</X_TWEAK>
					<TIMING>0.16</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-175</X_TWEAK>
					<TIMING>0.176</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-205</X_TWEAK>
					<TIMING>0.192</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-225</X_TWEAK>
					<TIMING>0.208</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-235</X_TWEAK>
					<TIMING>0.224</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.24</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<SIDE>left</SIDE>
					<TIMING>0.248</TIMING>
				</OBSTACLE>
			</CHUNK>

			<!-- Hard Slalom -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-220</X_TWEAK>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-160</X_TWEAK>
					<TIMING>0.016</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-130</X_TWEAK>
					<TIMING>0.032</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-90</X_TWEAK>
					<TIMING>0.048</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-60</X_TWEAK>
					<TIMING>0.064</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-40</X_TWEAK>
					<TIMING>0.08</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-30</X_TWEAK>
					<TIMING>0.096</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-25</X_TWEAK>
					<TIMING>0.112</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-25</X_TWEAK>
					<TIMING>0.128</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-30</X_TWEAK>
					<TIMING>0.144</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-40</X_TWEAK>
					<TIMING>0.16</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-60</X_TWEAK>
					<TIMING>0.176</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>				
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-90</X_TWEAK>
					<TIMING>0.192</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-130</X_TWEAK>
					<TIMING>0.208</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-180</X_TWEAK>
					<TIMING>0.224</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.24</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>

			<!-- The Wall Easy -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0175</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.035</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0525</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.095</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>

			<!-- The Wall Medium -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0175</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.035</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0525</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.07</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0875</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.125</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>


			<!-- The Wall Hard -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0175</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.035</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0525</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.07</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0875</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.105</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.1225</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.15</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>


			<!-- 5 Horizontal Lines (Easy) -->

			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0</TIMING>
					<X_TWEAK>123</X_TWEAK>
					<X_SCALE>0.5</X_SCALE>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.13</TIMING>
					<X_TWEAK>123</X_TWEAK>
					<X_SCALE>0.5</X_SCALE>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.26</TIMING>
					<X_TWEAK>123</X_TWEAK>
					<X_SCALE>0.5</X_SCALE>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.39</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>




			<!-- 5 Horizontal Lines (Medium) -->

			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<X_TWEAK>100</X_TWEAK>
					<X_SCALE>0.25</X_SCALE>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.05</TIMING>
					<X_TWEAK>100</X_TWEAK>
					<X_SCALE>0.25</X_SCALE>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.1</TIMING>
					<X_TWEAK>100</X_TWEAK>
					<X_SCALE>0.25</X_SCALE>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.15</TIMING>
					<X_TWEAK>100</X_TWEAK>
					<X_SCALE>0.25</X_SCALE>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.2</TIMING>
					<X_TWEAK>100</X_TWEAK>
					<X_SCALE>0.25</X_SCALE>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.25</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>



			<!-- 45 degree tri-line inverted -->

			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.09</TIMING>
					<ROTATION>40</ROTATION>
					<X_TWEAK>-40</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.11</TIMING>
					<ROTATION>40</ROTATION>
					<X_TWEAK>-80</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.13</TIMING>
					<ROTATION>40</ROTATION>
					<X_TWEAK>-120</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.15</TIMING>
					<ROTATION>40</ROTATION>
					<X_TWEAK>-160</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.17</TIMING>
					<ROTATION>40</ROTATION>
					<X_TWEAK>-200</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.19</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>

			<!-- The Bitshift Medium -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-220</X_TWEAK>
					<TIMING>0.0</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-44</X_TWEAK>
					<TIMING>0.0175</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-176</X_TWEAK>
					<TIMING>0.0175</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-88</X_TWEAK>
					<TIMING>0.035</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-132</X_TWEAK>
					<TIMING>0.035</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-132</X_TWEAK>
					<TIMING>0.0525</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-88</X_TWEAK>
					<TIMING>0.0525</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-176</X_TWEAK>
					<TIMING>0.07</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-44</X_TWEAK>
					<TIMING>0.07</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-220</X_TWEAK>
					<TIMING>0.0875</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0875</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.0965</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>


			<!-- The Bitshift Easy -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-220</X_TWEAK>
					<TIMING>0.0</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-55</X_TWEAK>
					<TIMING>0.0175</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-165</X_TWEAK>
					<TIMING>0.0175</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-110</X_TWEAK>
					<TIMING>0.035</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-110</X_TWEAK>
					<TIMING>0.035</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-165</X_TWEAK>
					<TIMING>0.0525</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-55</X_TWEAK>
					<TIMING>0.0525</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-220</X_TWEAK>
					<TIMING>0.07</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>0</X_TWEAK>
					<TIMING>0.07</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.079</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>


			<!-- The Bitshift Hard -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.0</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-80</X_TWEAK>
					<TIMING>0.0175</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-160</X_TWEAK>
					<TIMING>0.0175</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-160</X_TWEAK>
					<TIMING>0.035</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-80</X_TWEAK>
					<TIMING>0.035</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>-240</X_TWEAK>
					<TIMING>0.0525</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<X_TWEAK>0</X_TWEAK>
					<TIMING>0.0525</TIMING>
					<SIDE>right</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.061</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>

			

			<!-- 135 degree tri-line -->
			<CHUNK>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.0</TIMING>
					<ROTATION>-30</ROTATION>
					<X_TWEAK>-60</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.02</TIMING>
					<ROTATION>-30</ROTATION>
					<X_TWEAK>-100</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.04</TIMING>
					<ROTATION>-30</ROTATION>
					<X_TWEAK>-140</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.06</TIMING>
					<ROTATION>-30</ROTATION>
					<X_TWEAK>-180</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EasyRect</SHAPE>
					<TIMING>0.08</TIMING>
					<ROTATION>-30</ROTATION>
					<X_TWEAK>-220</X_TWEAK>
					<Y_TWEAK>0</Y_TWEAK>
					<SIDE>left</SIDE>
				</OBSTACLE>
				<OBSTACLE>
					<SHAPE>EndPiece</SHAPE>
					<TIMING>0.14</TIMING>
					<SIDE>left</SIDE>
				</OBSTACLE>
			</CHUNK>

			

		</CHUNKS>"		
	;
	
	public static string mediumObstacles = 
		@"<CHUNKS>
			
		</CHUNKS>"
	;

	public static String hardObstacles =
		@"<CHUNKS>
			
		</CHUNKS>"
	;
}
